### ISSUE TITLE
Can't reply to incoming message

### ISSUE THREAD

**Issue by dpaleino** [stonstad/NextLevel-HL7#1]
Hello,
I know it must be something obvious I'm missing... but I've been working on it for two days, without finding any clue on how to do it.

I need to reply to a message received: I started with the provided example, and am correctly processing incoming messages in my `OnMessageEvent()` method and `MessageProcessor` class
.
However, as soon as I try to reply to one of these messages (specifically, a `QRY` one), I obviously hit the wall of the socket being already in use.
I tried to save my reply in a variable outside of the event handler, with a couple of boolean values (like `isReplyReady` and `isAlreadySending`) and a running background thread that checks if there's anything ready to be sent, but I always hit the socket being already in use.

Is there any way to do this?

Thank you!

**Comment by stonstad** [comment]
Hi @dpaleino.  I reviewed the project's code and while the sample code successfully shows how an inbound and outbound interface is configured, it does not work in your scenario with a shared port.  To remedy this, you could use different ports for each interface. Alternatively, you may be able to share the socket connection between the inbound and outbound interfaces.  

* Create a method or property for accessing the socket --  private Socket _Socket = null; 
* Ensure the second interface (inbound or outbound) share the same socket.
* Ensure locking is performed as needed for multithreaded access to the socket, if applicable.

I currently am not engaged in a project which uses HL7 and for this reason, I won't be able to test a change.  However, I believe the behavior described above is the cause of the issue you are encountering.  I hope this helps.
